### ISSUE TITLE
Bug:当firstItem或Header的高度超过RecyclerView的显示高度时，会在没有滚至顶部时就拉出下拉刷新

### ISSUE THREAD

**Issue by pmavio** [captain-miao/RecyclerViewUtils#5]
原因：EndlessRecyclerOnScrollListener的checkCanBePulledDown方法仅对firstCompletelyVisibleItemPosition做了判断，当该值小于等于0，则判断为可拉出下拉刷新控件
`public boolean checkCanBePulledDown() {`
`int firstPos = mLinearLayoutManager.findFirstCompletelyVisibleItemPosition();`
`return firstPos <= 0;`
`}`
这样当item或header的高度超过一屏时，完全可见的item不存在，于是出现没有滚至顶部时就拉出下拉刷新的BUG。

解决方法如下
在WrapperRecyclerView中：
`return mEndlessRecyclerOnScrollListener.checkCanBePulledDown();`

替换为：
`if(getChildCount() == 0) return true;`
`int firstVisiblePosition = linearLayoutManager.findFirstVisibleItemPosition();`
`if(firstVisiblePosition != 0) return false;`
`View firstVisibleView = linearLayoutManager.findViewByPosition(firstVisiblePosition);`
`int top = firstVisibleView.getTop();`
`return  top >= 0;`

**Comment by captain-miao** [comment]
嗯 很好的fix，谢谢。
理解很深刻～
@pmavio

**Comment by captain-miao** [comment]
use ：

```
    //maybe you need refresh-dependencies first
    //./gradlew --refresh-dependencies
    com.github.captain-miao:recyclerviewutils:1.2.1-SNAPSHOT
```

**Comment by captain-miao** [comment]
for RecycleView

since support library 22.1, suggest using ViewCompat.canScrollVertically(recyclerView, -1) to check whether RecyclerView can scroll up.

RecyclerView now implements ScrollingView, which ViewCompat.canScrollVertically() really target to

from:https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/27#issuecomment-106761049
